<template>
  <section class="resource-page">
    <header class="page-header"><div><p class="eyebrow">DATA SERVICES</p><h1>数据库</h1><p class="page-description">运行隔离的 MySQL 或 PostgreSQL 数据库。</p></div><el-button type="primary" @click="dialog=true">创建数据库</el-button></header>
    <el-card shadow="never" class="resource-card"><div class="table-toolbar"><span class="record-count">{{ records.length }} 个实例</span><el-button text :loading="loading" @click="load">刷新</el-button></div>
      <el-table :data="records" v-loading="loading" empty-text="当前命名空间还没有数据库">
        <el-table-column label="数据库"><template #default="{row}"><div class="primary-cell"><span class="resource-avatar db-avatar">DB</span><div><strong>{{row.name}}</strong><small>{{row.dbname}}</small></div></div></template></el-table-column>
        <el-table-column label="引擎" width="150"><template #default="{row}"><el-tag effect="plain">{{row.dbtype}}</el-tag></template></el-table-column>
        <el-table-column label="规格" width="140"><template #default="{row}">{{row.cpu}} Core · {{row.memory}} GB</template></el-table-column>
        <el-table-column label="状态" width="120"><template #default="{row}"><el-tag :type="statusTag(row.status)" effect="plain">{{statusText(row.status)}}</el-tag></template></el-table-column>
        <el-table-column label="配置" width="170"><template #default="{row}"><span>{{restartPolicyText(row.restart_policy)}}</span><el-tag v-if="row.needs_recreate" type="warning" size="small" effect="plain" class="config-pending">需重建</el-tag></template></el-table-column>
        <el-table-column label="内网地址"><template #default="{row}">{{row.ip?.join(', ')||'—'}}</template></el-table-column>
        <el-table-column align="right" width="375"><template #default="{row}"><el-button link @click="openEdit(row)">编辑</el-button><el-button v-if="row.status==='running'" link :loading="operating===row.name" @click="setRunning(row,false)">停止</el-button><el-button v-if="row.status==='stopped'" link type="primary" :loading="operating===row.name" @click="setRunning(row,true)">启动</el-button><el-button link :disabled="row.status!=='running'" @click="exportSQL(row)">导出</el-button><el-button link :disabled="row.status!=='running'" @click="chooseImport(row)">导入</el-button><el-button link type="danger" :disabled="row.status==='importing'" @click="remove(row)">删除</el-button></template></el-table-column>
        <el-table-column align="right" width="65"><template #default="{row}"><el-button link @click="openLogs(row)">日志</el-button></template></el-table-column>
      </el-table><input ref="fileInput" hidden type="file" accept=".sql,application/sql" @change="importSQL" />
    </el-card>
  </section>
  <el-dialog v-model="logsDialog" :title="`${logsTarget?.name || ''} 实时日志`" width="900px">
    <div class="log-toolbar"><el-select v-model="logTail" class="tail-select" @change="connectLogs"><el-option label="最近 100 行" value="100"/><el-option label="最近 200 行" value="200"/><el-option label="最近 500 行" value="500"/><el-option label="最近 1000 行" value="1000"/></el-select><el-tag type="success" effect="plain">实时</el-tag></div>
    <pre class="log-output">{{ logs || '暂无日志，等待新输出…' }}</pre>
  </el-dialog>
  <el-dialog v-model="editDialog" :title="`编辑数据库 ${editTarget?.name || ''}`" width="520px"><el-form label-position="top"><el-form-item label="自动重启策略"><el-select v-model="editRestartPolicy"><el-option label="除非手动停止（推荐）" value="unless-stopped"/><el-option label="始终自动重启" value="always"/><el-option label="仅失败时重启" value="on-failure"/><el-option label="不自动重启" value="no"/></el-select></el-form-item><el-divider>日志策略</el-divider><el-form-item label="日志驱动"><el-select v-model="editLogDriver"><el-option label="local（推荐）" value="local"/><el-option label="json-file" value="json-file"/><el-option label="阿里云日志服务" value="aliyun-sls"/></el-select></el-form-item><div v-if="editLogDriver!=='aliyun-sls'" class="form-grid"><el-form-item label="单文件上限"><el-input v-model="editLogMaxSize" placeholder="10m"/></el-form-item><el-form-item label="保留文件数"><el-input-number v-model="editLogMaxFile" :min="1" :max="100"/></el-form-item></div><div v-else class="form-grid"><el-form-item label="Endpoint"><el-input v-model="editSLSEndpoint"/></el-form-item><el-form-item label="Project"><el-input v-model="editSLSProject"/></el-form-item><el-form-item label="Logstore"><el-input v-model="editSLSLogstore"/></el-form-item><el-form-item label="采集配置名称"><el-input v-model="editSLSConfigName"/></el-form-item></div><el-form-item label="立即应用"><el-switch v-model="editApplyNow"/><div class="form-hint">关闭时只保存配置并标记“需重建”；开启时会停止并重建容器，数据库卷会保留。</div></el-form-item></el-form><template #footer><el-button @click="editDialog=false">取消</el-button><el-button type="primary" :loading="editSaving" @click="saveEdit">保存</el-button></template></el-dialog>
  <el-dialog v-model="dialog" title="创建数据库" width="620px" destroy-on-close><el-form label-position="top" class="form-grid">
    <el-form-item label="实例名称" required><el-input v-model="form.name" placeholder="main-db"/></el-form-item><el-form-item label="数据库引擎"><el-select v-model="form.dbtype"><el-option label="MySQL 5.7" value="mysql:5.7"/><el-option label="MySQL 8.0" value="mysql:8.0"/><el-option label="PostgreSQL 16" value="postgres:16"/></el-select></el-form-item>
    <el-form-item label="数据库名" required><el-input v-model="form.dbname"/></el-form-item><el-form-item label="用户名" required><el-input v-model="form.username"/></el-form-item><el-form-item label="密码" required><el-input v-model="form.password" type="password" show-password/></el-form-item><el-form-item label="允许远程访问"><el-switch v-model="form.remote"/></el-form-item><el-form-item label="CPU (Core)"><el-input-number v-model="form.cpu" :min="0.5" :step="0.5"/></el-form-item><el-form-item label="内存 (GB)"><el-input-number v-model="form.memory" :min="0.5" :step="0.5"/></el-form-item><el-form-item label="自动重启策略" class="form-span"><el-select v-model="form.restart_policy"><el-option label="除非手动停止（推荐）" value="unless-stopped"/><el-option label="始终自动重启" value="always"/><el-option label="仅失败时重启" value="on-failure"/><el-option label="不自动重启" value="no"/></el-select><div class="form-hint">控制容器异常退出或服务器重启后的恢复行为。</div></el-form-item>
  </el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建数据库</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { onBeforeUnmount, reactive, ref, watch } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { api,type DatabaseRecord } from '../api';import { openLogStream,type LogStream } from '../logStream'
const props=defineProps<{namespace:string}>();const records=ref<DatabaseRecord[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false),fileInput=ref<HTMLInputElement>(),importTarget=ref<DatabaseRecord>(),operating=ref(''),editDialog=ref(false),editSaving=ref(false),editTarget=ref<DatabaseRecord>(),editRestartPolicy=ref('unless-stopped'),editLogDriver=ref('local'),editLogMaxSize=ref('10m'),editLogMaxFile=ref(3),editApplyNow=ref(false),editSLSProject=ref(''),editSLSLogstore=ref(''),editSLSEndpoint=ref(''),editSLSConfigName=ref('');const form=reactive({name:'',dbtype:'mysql:5.7',dbname:'',username:'',password:'',remote:false,cpu:1,memory:2,restart_policy:'unless-stopped'})
let pollTimer:number|undefined
const logsDialog=ref(false),logsTarget=ref<DatabaseRecord>(),logs=ref(''),logTail=ref('200')
let logsStream:LogStream|undefined
const reportedImportErrors=new Set<string>()
async function load(){loading.value=true;try{records.value=await api.get<DatabaseRecord[]>(`/namespaces/${props.namespace}/databases`)||[];for(const row of records.value){if(row.import_error){const key=`${row.name}:${row.import_error}`;if(!reportedImportErrors.has(key)){reportedImportErrors.add(key);ElMessage.error(`${row.name} 导入失败：${row.import_error}`)}}}updatePolling()}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
function updatePolling(){const importing=records.value.some(row=>row.status==='importing');if(importing&&pollTimer===undefined)pollTimer=window.setInterval(load,2000);if(!importing&&pollTimer!==undefined){window.clearInterval(pollTimer);pollTimer=undefined}}
function statusText(status?:string){return status==='running'?'运行中':status==='stopped'?'已停止':status==='missing'?'容器不存在':status==='paused'?'已暂停':status==='restarting'?'重启中':status==='importing'?'导入中':'未知'}
function statusTag(status?:string){return status==='running'?'success':status==='importing'||status==='restarting'?'warning':status==='missing'?'danger':'info'}
function restartPolicyText(value?:string){return value==='always'?'始终重启':value==='on-failure'?'失败时重启':value==='no'?'不自动重启':'除非手动停止'}
function openEdit(row:DatabaseRecord){editTarget.value=row;editRestartPolicy.value=row.restart_policy||'unless-stopped';editLogDriver.value=row.log_driver||'local';editLogMaxSize.value=row.log_max_size||'10m';editLogMaxFile.value=row.log_max_file||3;editSLSProject.value=row.sls_project||'';editSLSLogstore.value=row.sls_logstore||'';editSLSEndpoint.value=row.sls_endpoint||'';editSLSConfigName.value=row.sls_config_name||'';editApplyNow.value=false;editDialog.value=true}
async function saveEdit(){if(!editTarget.value)return;editSaving.value=true;try{await api.put(`/namespaces/${props.namespace}/databases/${editTarget.value.name}`,{restart_policy:editRestartPolicy.value,log_driver:editLogDriver.value,log_max_size:editLogMaxSize.value,log_max_file:editLogMaxFile.value,apply_now:editApplyNow.value,sls_project:editSLSProject.value,sls_logstore:editSLSLogstore.value,sls_endpoint:editSLSEndpoint.value,sls_config_name:editSLSConfigName.value});editDialog.value=false;ElMessage.success(editApplyNow.value?'数据库已按新配置重建':'配置已保存，等待重建');await load()}catch(e){ElMessage.error((e as Error).message)}finally{editSaving.value=false}}
async function setRunning(row:DatabaseRecord,running:boolean){operating.value=row.name;try{await api.post(`/namespaces/${props.namespace}/databases/${row.name}/${running?'start':'stop'}`);ElMessage.success(running?'数据库已启动':'数据库已停止');await load()}catch(e){ElMessage.error((e as Error).message)}finally{operating.value=''}}
async function create(){if(!form.name||!form.dbname||!form.username||!form.password)return ElMessage.warning('请填写必填项');saving.value=true;try{await api.post(`/namespaces/${props.namespace}/databases`,form);dialog.value=false;ElMessage.success('数据库已创建');load()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
function exportSQL(row:DatabaseRecord){window.open(`/api/v1/namespaces/${props.namespace}/databases/${row.name}/export`,'_blank')}
function chooseImport(row:DatabaseRecord){importTarget.value=row;fileInput.value?.click()}
async function importSQL(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file||!importTarget.value)return;try{const res=await fetch(`/api/v1/namespaces/${props.namespace}/databases/${importTarget.value.name}/import`,{method:'POST',headers:{'Content-Type':'application/sql'},body:file});if(!res.ok)throw new Error((await res.json()).error);ElMessage.success('SQL 上传完成，正在后台导入');await load()}catch(e){ElMessage.error((e as Error).message)}finally{input.value=''}}
async function remove(row:DatabaseRecord){try{await ElMessageBox.confirm(`确定删除数据库 “${row.name}” 及其数据卷吗？`,'删除数据库',{type:'warning'});await api.delete(`/namespaces/${props.namespace}/databases/${row.name}`);ElMessage.success('数据库已删除');load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}watch(()=>props.namespace,load,{immediate:true})
function openLogs(row:DatabaseRecord){logsTarget.value=row;logsDialog.value=true;connectLogs()}
function connectLogs(){if(!logsTarget.value)return;logsStream?.close();logs.value='';logsStream=openLogStream(`/namespaces/${props.namespace}/databases/${logsTarget.value.name}/logs?tail=${logTail.value}`,{onLog:chunk=>{logs.value+=chunk},onError:()=>ElMessage.error('数据库日志连接已断开')})}
watch(logsDialog,open=>{if(!open){logsStream?.close();logsStream=undefined}})
onBeforeUnmount(()=>{if(pollTimer!==undefined)window.clearInterval(pollTimer);logsStream?.close()})
</script>
<style scoped>
.log-toolbar { display: flex; align-items: center; gap: 10px; margin-bottom: 12px; }
.tail-select { width: 150px; }
.log-output { min-height: 440px; max-height: 60vh; margin: 0; padding: 16px; overflow: auto; border-radius: 8px; background: #101521; color: #d8e0ee; font: 12px/1.6 ui-monospace, SFMono-Regular, Consolas, monospace; white-space: pre-wrap; word-break: break-all; }
</style>
